== Test the deployment
// If steps are required to test the deployment, add them here. If not, remove the heading
This Quick Start includes CloudFormation output parameters that provide links to the infrastructure deployed by the Quick Start:

|===
|Output |Description

|RepoUrl |The URL to GitHub for creating a clone of the CodeCommit repository.
|LoadBalancerUrl |The URL for the Application Load Balancer in front of the Fargate service.
|CodePipelineUrl |The URL to navigate directly to the CodePipeline pipeline for the application.
|===
  
After deploying this Quick Start, a build of the application starts. You can use your browser to navigate to the CodePipeline URL to monitor the build process. After the build completes, you can navigate to the Application Load Balancer URL to view the application in your browser.

== Post-deployment steps
// If post-deployment steps are required, add them here. If not, remove the heading
Once you have deployed this Quick Start, you may use the CodeCommit repository URL to clone the repo and make modifications to the application. Any changes pushed to the repository will trigger an execution of the CodePipeline as well as a deployment of the application.
