// Include any postdeployment steps here, such as steps necessary to test that the deployment was successful. If there are no postdeployment steps, leave this file empty.

== Postdeployment steps

After you've deployed this Partner Solution, use the CodeCommit repository URL to clone the repo and make modifications to the application. When you push changes to the repo, the CodePipeline pipeline is triggered and the application deploys.

=== Test the deployment
// If steps are required to test the deployment, add them here. If not, remove the heading
This Partner Solution includes CloudFormation output parameters that provide links to the infrastructure deployed by the Partner Solution:

|===
|Output |Description

|RepoUrl |The URL to GitHub for creating a clone of the CodeCommit repository.
|LoadBalancerUrl |The URL for the Application Load Balancer in front of the Fargate service.
|CodePipelineName |The name of the CodePipeline CI/CD pipeline for the application.
|CodePipelineUrl |The URL to navigate directly to the CodePipeline CI/CD pipeline for the application.
|===
  
After deploying this Partner Solution, a build of the application starts. Use your browser to navigate to the CodePipeline URL to monitor the build process. After the build completes, navigate to the Application Load Balancer URL to view the application in your browser.

